[2025-10-10T06:05:31.305+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-10T06:05:31.346+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_analytics.retrain_model scheduled__2025-10-10T05:00:00+00:00 [queued]>
[2025-10-10T06:05:31.359+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_analytics.retrain_model scheduled__2025-10-10T05:00:00+00:00 [queued]>
[2025-10-10T06:05:31.369+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-10T06:05:31.392+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): retrain_model> on 2025-10-10 05:00:00+00:00
[2025-10-10T06:05:31.402+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3245) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-10T06:05:31.405+0000] {standard_task_runner.py:64} INFO - Started process 3247 to run task
[2025-10-10T06:05:31.405+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'restaurant_analytics', 'retrain_model', 'scheduled__2025-10-10T05:00:00+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_dag.py', '--cfg-path', '/tmp/tmpf49xwabf']
[2025-10-10T06:05:31.409+0000] {standard_task_runner.py:91} INFO - Job 321: Subtask retrain_model
[2025-10-10T06:05:31.504+0000] {task_command.py:426} INFO - Running <TaskInstance: restaurant_analytics.retrain_model scheduled__2025-10-10T05:00:00+00:00 [running]> on host dd5baa7fba45
[2025-10-10T06:05:31.649+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='quantruong1918@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='restaurant_analytics' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-10-10T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-10T05:00:00+00:00'
[2025-10-10T06:05:31.653+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-10T06:05:31.656+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-10T06:05:31.657+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'export PYSPARK_PYTHON=/usr/local/bin/python && export PYSPARK_DRIVER_PYTHON=/usr/local/bin/python && /opt/spark/bin/spark-submit --master local[*] /opt/***/dags/train_lr.py']
[2025-10-10T06:05:31.677+0000] {subprocess.py:86} INFO - Output:
[2025-10-10T06:05:38.850+0000] {subprocess.py:93} INFO - 25/10/10 06:05:38 INFO SparkContext: Running Spark version 3.5.1
[2025-10-10T06:05:38.853+0000] {subprocess.py:93} INFO - 25/10/10 06:05:38 INFO SparkContext: OS info Linux, 6.6.87.1-microsoft-standard-WSL2, amd64
[2025-10-10T06:05:38.860+0000] {subprocess.py:93} INFO - 25/10/10 06:05:38 INFO SparkContext: Java version 17.0.16
[2025-10-10T06:05:38.934+0000] {subprocess.py:93} INFO - 25/10/10 06:05:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-10-10T06:05:39.080+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO ResourceUtils: ==============================================================
[2025-10-10T06:05:39.082+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-10-10T06:05:39.083+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO ResourceUtils: ==============================================================
[2025-10-10T06:05:39.083+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO SparkContext: Submitted application: TrainLR
[2025-10-10T06:05:39.118+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-10-10T06:05:39.130+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO ResourceProfile: Limiting resource is cpu
[2025-10-10T06:05:39.132+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-10-10T06:05:39.202+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO SecurityManager: Changing view acls to: ***
[2025-10-10T06:05:39.204+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO SecurityManager: Changing modify acls to: ***
[2025-10-10T06:05:39.205+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO SecurityManager: Changing view acls groups to:
[2025-10-10T06:05:39.206+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO SecurityManager: Changing modify acls groups to:
[2025-10-10T06:05:39.207+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-10-10T06:05:39.612+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO Utils: Successfully started service 'sparkDriver' on port 35991.
[2025-10-10T06:05:39.681+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO SparkEnv: Registering MapOutputTracker
[2025-10-10T06:05:39.747+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO SparkEnv: Registering BlockManagerMaster
[2025-10-10T06:05:39.781+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-10-10T06:05:39.782+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-10-10T06:05:39.788+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-10-10T06:05:39.821+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-0e6806ad-90ae-4707-a87a-736f4662946b
[2025-10-10T06:05:39.841+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-10-10T06:05:39.865+0000] {subprocess.py:93} INFO - 25/10/10 06:05:39 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-10-10T06:05:40.087+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-10-10T06:05:40.223+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-10-10T06:05:40.438+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO Executor: Starting executor ID driver on host dd5baa7fba45
[2025-10-10T06:05:40.439+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO Executor: OS info Linux, 6.6.87.1-microsoft-standard-WSL2, amd64
[2025-10-10T06:05:40.443+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO Executor: Java version 17.0.16
[2025-10-10T06:05:40.457+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-10-10T06:05:40.459+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@5ad5c639 for default.
[2025-10-10T06:05:40.503+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45951.
[2025-10-10T06:05:40.504+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO NettyBlockTransferService: Server created on dd5baa7fba45:45951
[2025-10-10T06:05:40.507+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-10-10T06:05:40.522+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, dd5baa7fba45, 45951, None)
[2025-10-10T06:05:40.528+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO BlockManagerMasterEndpoint: Registering block manager dd5baa7fba45:45951 with 434.4 MiB RAM, BlockManagerId(driver, dd5baa7fba45, 45951, None)
[2025-10-10T06:05:40.533+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, dd5baa7fba45, 45951, None)
[2025-10-10T06:05:40.536+0000] {subprocess.py:93} INFO - 25/10/10 06:05:40 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, dd5baa7fba45, 45951, None)
[2025-10-10T06:05:41.264+0000] {subprocess.py:93} INFO - 25/10/10 06:05:41 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-10-10T06:05:41.275+0000] {subprocess.py:93} INFO - 25/10/10 06:05:41 INFO SharedState: Warehouse path is 'file:/tmp/***tmpx22tk_7v/spark-warehouse'.
[2025-10-10T06:05:43.166+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-10T06:05:43.167+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/train_lr.py", line 7, in <module>
[2025-10-10T06:05:43.170+0000] {subprocess.py:93} INFO -     df = spark.read.csv('historical_orders.csv', header=True, inferSchema=True)
[2025-10-10T06:05:43.170+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-10-10T06:05:43.171+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-10-10T06:05:43.173+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-10-10T06:05:43.174+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-10-10T06:05:43.183+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmpx22tk_7v/historical_orders.csv.
[2025-10-10T06:05:43.350+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO SparkContext: Invoking stop() from shutdown hook
[2025-10-10T06:05:43.351+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-10-10T06:05:43.369+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO SparkUI: Stopped Spark web UI at http://dd5baa7fba45:4040
[2025-10-10T06:05:43.386+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-10-10T06:05:43.404+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO MemoryStore: MemoryStore cleared
[2025-10-10T06:05:43.405+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO BlockManager: BlockManager stopped
[2025-10-10T06:05:43.413+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-10-10T06:05:43.417+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-10-10T06:05:43.431+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO SparkContext: Successfully stopped SparkContext
[2025-10-10T06:05:43.432+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO ShutdownHookManager: Shutdown hook called
[2025-10-10T06:05:43.433+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-2b7afeb2-4662-4dcf-a291-cfee35fe10b5
[2025-10-10T06:05:43.437+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-aba82301-74af-4974-85de-9bcdcdff49e4/pyspark-606470b9-0855-4831-9f98-a40482ec27be
[2025-10-10T06:05:43.442+0000] {subprocess.py:93} INFO - 25/10/10 06:05:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-aba82301-74af-4974-85de-9bcdcdff49e4
[2025-10-10T06:05:43.517+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-10T06:05:43.519+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-10T06:05:43.537+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-10T06:05:43.546+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=restaurant_analytics, task_id=retrain_model, run_id=scheduled__2025-10-10T05:00:00+00:00, execution_date=20251010T050000, start_date=20251010T060531, end_date=20251010T060543
[2025-10-10T06:05:43.577+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 321 for task retrain_model (Bash command failed. The command returned a non-zero exit code 1.; 3247)
[2025-10-10T06:05:43.622+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-10T06:05:43.652+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-10T06:05:43.667+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
